name: anri
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  particles_flutter: ^0.1.4
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.1
  timeago: ^3.6.1
  flutter_html: ^3.0.0
  flutter_dotenv: ^5.1.0
  photo_view: ^0.15.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  file_picker: ^8.0.6
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.3.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/anri_logo.png
    - assets/images/label-critical.png
    - assets/images/label-high.png
    - assets/images/label-medium.png
    - assets/images/label-low.png
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true             
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21